import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        }
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: [
        {
          type: 'autogenerated',
          dirName: 'about',
        }
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        {
          type: 'autogenerated',
          dirName: 'architecture',
        }
      ],
    },
  ],

  // Reference documentation sidebar
  referenceSidebar: [
    {
      type: 'category',
      label: 'CLI Commands',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/cli',
        }
      ],
    },
    {
      type: 'category',
      label: 'Services API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/api',
        }
      ],
    },
    {
      type: 'category',
      label: 'AI Assistants',
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/assistants',
        }
      ],
    },
  ],

  // Contributing documentation sidebar
  contributingSidebar: [
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing',
        }
      ],
    },
  ],
};

export default sidebars;
