import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        }
      ],
    },
    {
      type: 'category',
      label: 'About',
      items: [
        {
          type: 'autogenerated',
          dirName: 'about',
        }
      ],
    },
  ],

  // Reference documentation sidebar
  referenceSidebar: [
    {
      type: 'doc',
      id: 'reference/index',
      label: 'Reference',
    },
    {
      type: 'category',
      label: 'Services',
      link: { type: 'doc', id: 'reference/services/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/services',
        }
      ],
    },
    {
      type: 'category',
      label: 'AI Assistants',
      link: { type: 'doc', id: 'reference/assistants/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/assistants',
        }
      ],
    },
    {
      type: 'category',
      label: 'Data Models',
      link: { type: 'doc', id: 'reference/models/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/models',
        }
      ],
    },
    {
      type: 'category',
      label: 'Utilities',
      link: { type: 'doc', id: 'reference/utils/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/utils',
        }
      ],
    },
    {
      type: 'category',
      label: 'Core',
      link: { type: 'doc', id: 'reference/core/index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'reference/core',
        }
      ],
    },
  ],

  // Contributing documentation sidebar
  contributingSidebar: [
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing',
        }
      ],
    },
  ],
};

export default sidebars;
